### ISSUE TITLE
Columns in left wiring diagram seem mirrored

### ISSUE THREAD

**Issue by BuysDB** [thlintw/clavert#1]
Hi, first of thanks a lot for this repo. I never built a keyboard before and I was able to build this set based on your instructions and this went really well, and it is fully working now. Sweet. 
There was one small thing I ran into: in the wiring diagram the column connections to the nice!nano are mirrored. (Should be D20 to the leftmost key-column on the diagram). 
ps : Maybe you could also add some rubber feet to the BOM?

**Comment by thlintw** [comment]
Yeah that seems to be the case sorry about that. I'll fix that soon.
